package validate

import "github.com/go-playground/validator"

const (
	VALIDATE_TAG_CAPTCHA = "captcha"

	CAPTCHA_UNKNOWN = iota
	CAPTCHA_REGISTER
	CAPTCHA_LOGIN
	CAPTCHA_RESET_PASSWORD
	CAPTCHA_CHANGE_EMAIL
	CAPTCHA_CHANGE_PHONE
	CAPTCHA_AUTH
	CAPTCHA_RESERVATION_PROTOCOL_FIRST
	CAPTCHA_RESERVATION_PROTOCOL_SECOND
	CAPTCHA_RESERVATION_PROTOCOL_THIRD
	CAPTCHA_RESERVATION_PROTOCOL_FOURTH
	CAPTCHA_RESERVATION_PROTOCOL_FIFTH
	CAPTCHA_RESERVATION_PROTOCOL_SIXTH
	CAPTCHA_RESERVATION_PROTOCOL_SEVENTH
	CAPTCHA_RESERVATION_PROTOCOL_EIGHTH
)

func validateTagCaptcha(fl validator.FieldLevel) bool {
	captcha_type_value := fl.Field().Uint()

	switch captcha_type_value {
	case uint64(CAPTCHA_UNKNOWN),
		uint64(CAPTCHA_REGISTER),
		uint64(CAPTCHA_LOGIN),
		uint64(CAPTCHA_RESET_PASSWORD),
		uint64(CAPTCHA_CHANGE_EMAIL),
		uint64(CAPTCHA_CHANGE_PHONE),
		uint64(CAPTCHA_AUTH),
		uint64(CAPTCHA_RESERVATION_PROTOCOL_FIRST),
		uint64(CAPTCHA_RESERVATION_PROTOCOL_SECOND),
		uint64(CAPTCHA_RESERVATION_PROTOCOL_THIRD),
		uint64(CAPTCHA_RESERVATION_PROTOCOL_FOURTH),
		uint64(CAPTCHA_RESERVATION_PROTOCOL_FIFTH),
		uint64(CAPTCHA_RESERVATION_PROTOCOL_SIXTH),
		uint64(CAPTCHA_RESERVATION_PROTOCOL_SEVENTH),
		uint64(CAPTCHA_RESERVATION_PROTOCOL_EIGHTH):
		return true
	}

	return false
}
