package validate

import "github.com/go-playground/validator"

const (
	VALIDATE_TAG_GENDER = "gender"
)

const (
	GENDER_UNKNOWN = iota
	GENDER_MALE
	GENDER_FEMALE
	GENDER_RESERVATION_PROTOCOL_FIRST
	GENDER_RESERVATION_PROTOCOL_SECOND
	GENDER_RESERVATION_PROTOCOL_THIRD
	GENDER_RESERVATION_PROTOCOL_FOURTH
	GENDER_RESERVATION_PROTOCOL_FIFTH
	GENDER_RESERVATION_PROTOCOL_SIXTH
	GENDER_RESERVATION_PROTOCOL_SEVENTH
	GENDER_RESERVATION_PROTOCOL_EIGHTH
)

func validateTagGender(fl validator.FieldLevel) bool {
	gender := fl.Field().Uint()

	switch gender {
	case uint64(GENDER_UNKNOWN),
		uint64(GENDER_MALE),
		uint64(GENDER_FEMALE),
		uint64(GENDER_RESERVATION_PROTOCOL_FIRST),
		uint64(GENDER_RESERVATION_PROTOCOL_SECOND),
		uint64(GENDER_RESERVATION_PROTOCOL_THIRD),
		uint64(GENDER_RESERVATION_PROTOCOL_FOURTH),
		uint64(GENDER_RESERVATION_PROTOCOL_FIFTH),
		uint64(GENDER_RESERVATION_PROTOCOL_SIXTH),
		uint64(GENDER_RESERVATION_PROTOCOL_SEVENTH),
		uint64(GENDER_RESERVATION_PROTOCOL_EIGHTH):
		return true
	}

	return false
}
